import { outfit } from '@/lib/fonts'
import './globals.css'
import Providers from './providers'
import { Toaster } from '@/components/ui/toaster'

export const metadata = {
  title: 'Starter',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={outfit.className}>
        <Providers>
          {children}
        </Providers>
        <Toaster />
      </body>
    </html>
  )
}
